name = "myt-backend"
main = "index.js" # Aapki main file ka naam (check karlo index.js hai ya kuch aur)
compatibility_date = "2026-05-10"

[vars]
# Yahan variables ki jagah khali chhod do, hum dashboard se bharenge
